Master (#1)
* Created last services added to eShop
Updated with latest configurations

* Update ARM template

* Improve build-bits-linux.sh (removed dotnet restore (doing with publish now)  and set quiet on verbosity in order to reduce issues with System.Console.dll on build container). Remove unnecesary namespace on Identity.Api startup.cs

* dotnet restore not needed in cli 2.0

"Starting with .NET Core 2.0 SDK, dotnet restore runs implicitily when you run dotnet build." (C) https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x

* dotnet restore not needed in cli 2.0

"Starting with .NET Core 2.0 SDK, dotnet restore runs implicitily when you run dotnet build." (C) https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x

* sync k8 images with local windows/linux images for consistency

* Added PathBase WebMVC

* Test base_path

* Base path fix and k8s config updated

* Rename connectionstring variable in Idsrv

* Added SuffixPath attr to service endpoints
Added SetBasePath env. var setting to services

* Migrated Identity.API to Identity Server 4 on dotnetcore2

* Created WebMVC, WebSPA and Webstatus SF application project.
Created IdentityServer SF application project

* Fix migrations for new identity server, fix new program template for dotnetcore2

* Update identity.api base image to aspnetcore2.0
Rename Identity.api namespace

* Updated ARM SF templates

* Added images for SF as windows containers deployment docu

* Refactoring all dbcontext seed using new MigrateDbContext extension method on IWebHost. This prevent errors when using dotnet ef cli and seeders in Startup

* Update ARM template for SF deployment

* Treat *.pfx as binary so CRLF will not change it

* Added BasePath to swagger endpoint
Override environment variables urls

* Rename Basket.cs to CustomerBasket.cs

* Fix the "missing sub claim"

* Fix view models namespaces issues. Remove unnecessary design time ordering context provider

* Update aspnetcore HealthCheck to 2.0

* Added WebHost.Customization.csproj to eShopOnContainers-MobileApps sln

* Create DesignTimeFactories for context used on startup with dependencies

* Update sln version

* fix namespaces in LoginPartial

* Fix issue with AddAuthentication and no default Schema on Marketing.API

* Create polygons by continent in LocationsContextSeed db

* Fix Authentication issue in Locations.api
Created input in user campaigns view to update the user's location

* Added Reverse Proxy LB Rule to ARM template

* Grace period rudement fix

* k8 grace period

* We don't need swagger and MVC contollers in Payment API

* Health check for Payment

* we don't need schema files for k8 in a repo.

* Update README.k8s.md

* Update README.k8s.md

* Fix namespace in RAZOR page _LoginPartial.cshtml, so nocompilation error when doing dotnet publish from CLI. Like D:\GITREPOS\eShopOnContainers-dev\src\Services\Identity\Identity.API\Views\Shared\_LoginPartial.cshtml(2,20): error CS0234: The type
 or namespace name 'Models' does not exist in the namespace 'Identity.API' (are you missing an assembly reference?)

* Minor comment fixed

* Update k8s conf_local with GracePeriodManager mandatory settings

* Update k8s deployment and compose files with graceperiodmanager settings missing

* Added missing entries for k8s

* Reverted net standard libraries to pcl

* Changes in csprojs

* Created new PCL projects to fix compilation in Visual Studio for macOS

* Changed minimum deployment target to iOS 9.

This ensures the launch storyboard doesn’t generate an error, and is
line with Xamarin policy for samples.

* Removed async warning.

* Invert Lat/Long order on Marketing Campaign Views

* fix errors in configmap for k8s

* Windows test runner uses same target version as Windows app.

* Minor solution changes for latest VS2017 release.

* Fixed miroservices spelling mistake

* Fixed bindings errors
Fixed Checkout process
Changed some UWP icons

* Set NO-CACHE for HealthCheck to Basket microservice, and MVC and SPA apps so it is faster for demoing HealthChecks.

* Fixed header typo.

* Update cloud manifest

* Explicitly specifying parameters for az acs creat

Non-preview parameters specified

* Fix issue k8s webstatus: webmvc healthcheck fails
Added Payment.api to healthcheck

* New campaign icons for iOS + Android #353

* UWP campaign icon. Fixes #353

* Fixed relationship between XAML and their code-behind files in the PCL. Fixes #354

* Fixed SplashScreen implementation on Android. Fixes #355

The MainTheme set the splash screen image as the window background.
I’ve removed this and ensured that the SplashActivity is the launch
activity.

Also did some code tidy up on the Campaign page classes.

* Integrate HealthCheck with k8s

* Added swagger to Payment.api

* Updated marketing.api service fabric env. vars

* Updates marketing.api SF manifest

* Git test

* Update build-bits.sh

* Update README.md

* Set Linux as by default target OS for Docker's project in VS2017

* Removed Service Fabric manifests targeting Windows from default eShopOnContainers VS solution which targets Docker Linux

* Added Microservices eBooks for eReaders like Kindle, etc. (.MOBI and .EPUB)

* Update docker-compose.yml

fix mssql version

* Created ARM template for deploying a secured SF
Created ps1 to generate certificates in keyvault
Updated readme

* Revert "Update docker-compose.yml"

* Changed to new GA SQL Server container Image tag and parameters

* Added links to eReader formats (Kindle/MOBI and EPUB)

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Remove hardcoded database name from GracePeriodManagerService

* Removed swagger from Payment.api

* build script with no parallel msbuild. For using with VSTS (parallel builds seems to cause that some builds fail randomly)

* Updated all docker-compose files version from 2.1 to 3

* Added eShopOnServiceFabric project for Linux

* Created deployment scripts for SF Linux

* Created SF infrastucture services

* Update SF linux manifests

* Updated sf linux image tags

* Update catalog.api sf env var

* Update README.md

Fixed small typo noticed while scanning ReadMe. will thoroughly read later.

* Update readme.md

* Update readme.md

* Update README.md

* Update README.md

* Update README.md

* UPdate with API Gateway info

* Updated the main README and eShopOnContainers architecture diagrams

* README updated

* README updated

* README updated in regards Azure API Management

* Updated README in regards the databases

* Minor update in README

* Set Retries with exponential backoff to most microservices sqlOptions, so errors when spinning the SQL container late shouldn't happen.

* Removed the mssql folder...

* Added AppInsights service

* Added Appinsights K8s telemetry initializer

* Fix for regression bug at AddDbContext<IntegrationEventLogContext> for Catalog.API

* Missing fix

* Fixed bug about loggerFactory and ConfigureAuthService() at MArketing.API Startup.cs

* Update README.md

* Update README.md

* swagge responce types and code https://github.com/dotnet-architecture/eShopOnContainers/issues/305

* retry policy defined via config

* identity4 2.0 rtm

* Payment API orchestrator fix

* Increased number of retries with exponential backoff and Circuir-Breaker so minimizes the risk of open circuit when spinning up the containers for the first time in Docker.

* Added Appinsights Linux SF telemetry initializer

* Added Appinsights Windows SF telemetry initializer

* packages update and clean up *.csproj files from useless content

* update to latest packages

* Update README.md

Fixed small typos.

* Updated SF Linux manifests

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update for servicefabricdeploy.parameters.json files for Windows and Linux

* Updates to servicefabricdeploy.parameters.json file

* Update to servicefabricdeploy.parameters.json file for Windows

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Updates to servicefabricdeploy.parameters.json files

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Updates to servicefabricdeploysecured.parameters.json files

* Update to servicefabricdeploysecured.parameters.json file

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Update readme.md

* Updated SF Windows manifests
Set single instance per SF service

* Change AccessMethod in load tests to Sequential

* last .net core 2.0 part

* js file is not exists

* Revert "last .net core 2.0 part"

* Fix Unit, Integration and Functional Tests

* Fix for the PackageReference Include="StackExchange.Redis" regression bug at DataProtection.csproj which was referencing a local Redis.StrongName package

* Fix issue StackExchange.Redis strongname

* Updated Load Tests
Added middleware to bypass authorization in load testing

* Created new load test scenarios

* Update project list in mac build script

* Removed unneeded reference.

* Added a Style to define the margin on Entry controls on the SettingsView. Fixes #387

* Removed unused methods.

* Whitespace removed.

* Increased maxRetryCount (number of retries) of EFDbContext trying to connect to the ASP.NET Identity database so EF migrations is run properly if the SQL container starts up slower.

* Updated settings for k8s / SF to enable Load testing mode
Updated load tests

* Added placeholder for eshop image tags in SF config manifests

* Update readme

* Fixed certain typos in README.md file